name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # oder der Branch, von dem du deployen möchtest
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "PAGE_URL=$PAGE_URL"
          echo "WORDPRESS_API_URL=$WORDPRESS_API_URL"
          echo "WORKFLOW_BUILD=$WORKFLOW_BUILD"
        env:
          PAGE_URL: ${{ secrets.PAGE_URL }}
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
          WORKFLOW_BUILD: "true"
      - name: Build and Export Next.js
        run: npm run build
        env:
          PAGE_URL: ${{ secrets.PAGE_URL }}
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
          WORKFLOW_BUILD: "true"
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_CMS_MODE: "static"

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: out  # Standard-Output-Verzeichnis von `next export`
