name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # oder der Branch, von dem du deployen möchtest
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build and Export Next.js
        run: npm run build
        env:
          PAGE_URL: ${{ secrets.PAGE_URL }}
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
          WORKFLOW_BUILD: "true"
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_CMS_MODE: "static"

      - name: list output
        run: ls -all out/

      - name: Archive static export
        run: |
          cd out
          zip -r ../next-export.zip .
          cd ..

      # 📦 Bereitstellen als GitHub-Artefakt
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-export
          path: next-export.zip
